services:
    backend:
        build:
            context: .
            dockerfile: backend/Dockerfile
        volumes:
            - ./config.py:/app/config.py:ro
        ports:
            - '8000:8000'
        # Завантажуємо змінні з .env файлу
        env_file:
            - .env
        # Також можна передавати змінні тут, якщо потрібно
        environment:
            # - ALLOWED_ORIGINS=http://localhost # Ця змінна не використовується в app.py, її можна видалити або передати з .env
            - SECRET_KEY=${SECRET_KEY} # Ця змінна буде взята з .env завдяки env_file

    frontend:
        build:
            context: .
            dockerfile: frontend/Dockerfile
        ports:
            - '8002:80'
        depends_on:
            - backend
